# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b800f30d202ceb6820919230e4cd0668a882bac5e14316b537d9d80a55c90fe42b9ab234616f283b3bdcbf1ce8c2399e553d542febc9f8c9521dd1cc03d231

test:
  secret_key_base: 15ced873e737ed67eaa2e60ee9b29308e64aecfc1c2728e2210e938e28c94bd2769d9d3667fa538151f18bb26493cf269596541e85b94edea3415cd3adc6c833

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
